//! Cache Span Tagging System
//!
//! Provides semantic metadata tracking for regions of the KV cache without storing
//! the actual token content. Spans are lightweight metadata overlays that enable:
//!
//! - **Semantic Grouping**: Tag cache regions by type (SystemPrompt, ToolOutput, etc.)
//! - **Coordinated Eviction**: Parent-child dependencies ensure related spans evict together
//! - **Priority Management**: Importance scores integrate with eviction voting system
//! - **Overlapping Spans**: Multiple tags can reference the same cache positions
//! - **External Storage**: Token content managed separately (memory, disk, vector DB)
//!
//! # Design Philosophy
//!
//! **CacheSpan = Metadata Only**
//!
//! Spans do NOT store tokens - they're just labels on cache regions. This separation enables:
//! - Flexible storage (memory, disk, vector DB)
//! - Memory control (unload tokens but keep metadata)
//! - Vector DB integration (semantic search using SpanId as key)
//!
//! # Example Usage
//!
//! ```rust,ignore
//! // External token storage (your choice!)
//! let mut token_storage: HashMap<SpanId, Vec<u32>> = HashMap::new();
//!
//! // Create span for system prompt
//! let span_id = builder.begin_span(
//!     slot: 0,
//!     pos: 0,
//!     tag: CacheTag::SystemPrompt,
//!     name: Some("sys_prompt_v1".into())
//! )?;
//!
//! // Store tokens externally
//! token_storage.insert(span_id, system_prompt_tokens);
//!
//! // Later: evict span
//! let result = builder.evict_span(span_id)?;
//!
//! // Handle eviction (move to disk, vector DB, etc.)
//! for (evicted_span_id, impact) in result.spans_affected {
//!     if matches!(impact, EvictionImpact::FullyEvicted) {
//!         if let Some(tokens) = token_storage.remove(&evicted_span_id) {
//!             save_to_vector_db(evicted_span_id, &tokens)?;
//!         }
//!     }
//! }
//! ```

use std::collections::HashMap;
use std::ops::Range;

/// Unique identifier for a cache span
pub type SpanId = u64;

/// Semantic tags for categorizing cache spans
///
/// These provide type-safe grouping of spans by their semantic role.
/// Use `Custom` with a name for domain-specific tags.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CacheTag {
    /// System prompt or instructions
    SystemPrompt,
    /// User input text
    UserInput,
    /// Output from tool execution
    ToolOutput,
    /// Long-term memory context
    LongTermMemory,
    /// Text generated by the model
    ModelGeneration,
    /// Custom tag (use name field for identification)
    Custom,
}

/// Current state of a cache span
#[derive(Debug, Clone, PartialEq)]
pub enum SpanState {
    /// Span is fully present in the cache
    Active,
    /// Span has been partially evicted
    /// Remaining positions are still valid in the cache
    PartiallyEvicted {
        /// Position ranges that are still valid
        remaining_ranges: Vec<Range<usize>>,
    },
    /// Span has been completely evicted from the cache
    FullyEvicted,
}

/// Impact of eviction on a specific span
#[derive(Debug, Clone, PartialEq)]
pub enum EvictionImpact {
    /// Span was completely evicted
    FullyEvicted,
    /// Span was partially evicted (some positions remain valid)
    PartiallyEvicted {
        /// Position ranges that are still valid
        remaining: Vec<Range<usize>>,
    },
    /// Span unchanged (other spans still reference these positions)
    Unchanged,
}

/// Result of an eviction operation
///
/// Provides explicit information about what was affected by eviction.
/// Caller can use this to coordinate external storage (disk, vector DB, etc.)
#[derive(Debug, Clone)]
pub struct EvictionResult {
    /// Spans affected by this eviction and how they were impacted
    pub spans_affected: Vec<(SpanId, EvictionImpact)>,
    /// Cache positions that were actually evicted (slot, position_range)
    pub positions_evicted: Vec<(usize, Range<usize>)>,
}

impl EvictionResult {
    /// Create an empty eviction result (nothing was evicted)
    pub fn empty() -> Self {
        Self {
            spans_affected: Vec::new(),
            positions_evicted: Vec::new(),
        }
    }

    /// Check if any spans were fully evicted
    pub fn has_fully_evicted(&self) -> bool {
        self.spans_affected
            .iter()
            .any(|(_, impact)| matches!(impact, EvictionImpact::FullyEvicted))
    }

    /// Get IDs of all fully evicted spans
    pub fn fully_evicted_span_ids(&self) -> Vec<SpanId> {
        self.spans_affected
            .iter()
            .filter_map(|(id, impact)| {
                if matches!(impact, EvictionImpact::FullyEvicted) {
                    Some(*id)
                } else {
                    None
                }
            })
            .collect()
    }
}

/// Metadata for a cache span
///
/// Tracks semantic information about a region of the KV cache.
/// Does NOT store tokens - that's the caller's responsibility.
#[derive(Debug, Clone)]
pub struct CacheSpan {
    /// Unique identifier
    pub id: SpanId,
    /// Which batch slot this span belongs to
    pub slot: usize,
    /// Starting position in the sequence
    pub start_pos: usize,
    /// Ending position in the sequence (exclusive)
    pub end_pos: usize,
    /// Semantic tag for grouping
    pub tag: CacheTag,
    /// Optional unique name for human reference
    pub name: Option<String>,
    /// Importance score for eviction priority (0.0 = evict first, 1.0 = evict last)
    pub importance: f32,
    /// Parent span (for dependency tracking)
    pub parent: Option<SpanId>,
    /// Child spans (auto-evict when this span is evicted)
    pub children: Vec<SpanId>,
    /// Current state of the span
    pub state: SpanState,
}

impl CacheSpan {
    /// Create a new active span
    pub fn new(
        id: SpanId,
        slot: usize,
        start_pos: usize,
        end_pos: usize,
        tag: CacheTag,
        name: Option<String>,
    ) -> Self {
        Self {
            id,
            slot,
            start_pos,
            end_pos,
            tag,
            name,
            importance: 0.5, // Default: neutral importance
            parent: None,
            children: Vec::new(),
            state: SpanState::Active,
        }
    }

    /// Get the length of this span in tokens
    pub fn len(&self) -> usize {
        self.end_pos.saturating_sub(self.start_pos)
    }

    /// Check if this span is empty
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Check if this span is currently active
    pub fn is_active(&self) -> bool {
        matches!(self.state, SpanState::Active)
    }

    /// Check if this span is fully evicted
    pub fn is_fully_evicted(&self) -> bool {
        matches!(self.state, SpanState::FullyEvicted)
    }

    /// Check if a position falls within this span
    pub fn contains_position(&self, pos: usize) -> bool {
        pos >= self.start_pos && pos < self.end_pos
    }

    /// Check if this span overlaps with a position range
    pub fn overlaps_range(&self, start: usize, end: usize) -> bool {
        !(end <= self.start_pos || start >= self.end_pos)
    }
}

/// Registry for managing cache spans
///
/// Provides storage and lookup for spans with support for:
/// - Unique SpanId generation
/// - Unique name enforcement
/// - Parent-child relationship tracking
/// - Tag-based queries
#[derive(Debug)]
pub struct SpanRegistry {
    /// All spans indexed by ID
    spans: HashMap<SpanId, CacheSpan>,
    /// Name to ID mapping (enforces uniqueness)
    name_to_id: HashMap<String, SpanId>,
    /// Next available span ID
    next_id: SpanId,
}

impl SpanRegistry {
    /// Create a new empty registry
    pub fn new() -> Self {
        Self {
            spans: HashMap::new(),
            name_to_id: HashMap::new(),
            next_id: 1, // Start at 1 (0 reserved for "no span")
        }
    }

    /// Generate a new unique SpanId
    pub fn next_span_id(&mut self) -> SpanId {
        let id = self.next_id;
        self.next_id = self.next_id.wrapping_add(1);
        id
    }

    /// Register a new span
    ///
    /// Returns error if name already exists
    pub fn register(&mut self, span: CacheSpan) -> Result<SpanId, String> {
        // Check name uniqueness
        if let Some(ref name) = span.name {
            if self.name_to_id.contains_key(name) {
                return Err(format!("Span name '{}' already exists", name));
            }
        }

        let id = span.id;

        // Register name if present
        if let Some(ref name) = span.name {
            self.name_to_id.insert(name.clone(), id);
        }

        // Store span
        self.spans.insert(id, span);

        Ok(id)
    }

    /// Get a span by ID
    pub fn get(&self, id: SpanId) -> Option<&CacheSpan> {
        self.spans.get(&id)
    }

    /// Get a mutable span by ID
    pub fn get_mut(&mut self, id: SpanId) -> Option<&mut CacheSpan> {
        self.spans.get_mut(&id)
    }

    /// Find a span by name
    pub fn find_by_name(&self, name: &str) -> Option<&CacheSpan> {
        self.name_to_id.get(name).and_then(|id| self.spans.get(id))
    }

    /// Get all spans with a specific tag
    pub fn spans_with_tag(&self, tag: CacheTag) -> Vec<&CacheSpan> {
        self.spans.values().filter(|span| span.tag == tag).collect()
    }

    /// Get all spans for a specific slot
    pub fn spans_for_slot(&self, slot: usize) -> Vec<&CacheSpan> {
        self.spans
            .values()
            .filter(|span| span.slot == slot)
            .collect()
    }

    /// Remove a span from the registry
    ///
    /// Returns the removed span if it existed
    pub fn remove(&mut self, id: SpanId) -> Option<CacheSpan> {
        let span = self.spans.remove(&id)?;

        // Remove name mapping if present
        if let Some(ref name) = span.name {
            self.name_to_id.remove(name);
        }

        Some(span)
    }

    /// Get all child span IDs (recursive)
    pub fn get_all_children(&self, id: SpanId) -> Vec<SpanId> {
        let mut result = Vec::new();
        let mut to_process = vec![id];

        while let Some(current_id) = to_process.pop() {
            if let Some(span) = self.spans.get(&current_id) {
                for &child_id in &span.children {
                    if !result.contains(&child_id) {
                        result.push(child_id);
                        to_process.push(child_id);
                    }
                }
            }
        }

        result
    }

    /// Check if adding a parent would create a cycle
    pub fn would_create_cycle(&self, child_id: SpanId, parent_id: SpanId) -> bool {
        // Walk up from parent to see if we reach child
        let mut current = Some(parent_id);
        while let Some(id) = current {
            if id == child_id {
                return true; // Cycle detected
            }
            current = self.spans.get(&id).and_then(|s| s.parent);
        }
        false
    }

    /// Get count of active spans
    pub fn active_span_count(&self) -> usize {
        self.spans.values().filter(|s| s.is_active()).count()
    }

    /// Find all spans that overlap with a given position range
    ///
    /// Returns spans where [span.start_pos, span.end_pos) intersects with [start, end)
    pub fn spans_overlapping_range(
        &self,
        slot: usize,
        start: usize,
        end: usize,
    ) -> Vec<&CacheSpan> {
        self.spans
            .values()
            .filter(|span| span.slot == slot && span.start_pos < end && span.end_pos > start)
            .collect()
    }

    /// Clear all spans
    pub fn clear(&mut self) {
        self.spans.clear();
        self.name_to_id.clear();
    }
}

impl Default for SpanRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_span_creation() {
        let span = CacheSpan::new(1, 0, 0, 100, CacheTag::SystemPrompt, Some("test".into()));
        assert_eq!(span.id, 1);
        assert_eq!(span.len(), 100);
        assert!(span.is_active());
        assert!(!span.is_fully_evicted());
    }

    #[test]
    fn test_span_contains_position() {
        let span = CacheSpan::new(1, 0, 10, 20, CacheTag::UserInput, None);
        assert!(!span.contains_position(9));
        assert!(span.contains_position(10));
        assert!(span.contains_position(15));
        assert!(span.contains_position(19));
        assert!(!span.contains_position(20));
    }

    #[test]
    fn test_span_overlaps_range() {
        let span = CacheSpan::new(1, 0, 10, 20, CacheTag::UserInput, None);
        assert!(!span.overlaps_range(0, 10)); // Ends at our start
        assert!(span.overlaps_range(5, 15)); // Overlaps
        assert!(span.overlaps_range(15, 25)); // Overlaps
        assert!(!span.overlaps_range(20, 30)); // Starts at our end
    }

    #[test]
    fn test_registry_unique_names() {
        let mut registry = SpanRegistry::new();

        let span1 = CacheSpan::new(1, 0, 0, 10, CacheTag::SystemPrompt, Some("test".into()));
        assert!(registry.register(span1).is_ok());

        let span2 = CacheSpan::new(2, 0, 10, 20, CacheTag::UserInput, Some("test".into()));
        assert!(registry.register(span2).is_err()); // Duplicate name
    }

    #[test]
    fn test_registry_find_by_name() {
        let mut registry = SpanRegistry::new();
        let span = CacheSpan::new(1, 0, 0, 10, CacheTag::SystemPrompt, Some("test".into()));
        registry.register(span).unwrap();

        let found = registry.find_by_name("test");
        assert!(found.is_some());
        assert_eq!(found.unwrap().id, 1);

        assert!(registry.find_by_name("nonexistent").is_none());
    }

    #[test]
    fn test_registry_cycle_detection() {
        let mut registry = SpanRegistry::new();

        let span1 = CacheSpan::new(1, 0, 0, 10, CacheTag::SystemPrompt, None);
        let mut span2 = CacheSpan::new(2, 0, 10, 20, CacheTag::UserInput, None);
        span2.parent = Some(1);

        registry.register(span1).unwrap();
        registry.register(span2).unwrap();

        // Try to make span1's parent = span2 (would create cycle)
        assert!(registry.would_create_cycle(1, 2));
        assert!(!registry.would_create_cycle(2, 1)); // Already parent, not a cycle
    }

    #[test]
    fn test_eviction_result() {
        let result = EvictionResult {
            spans_affected: vec![
                (1, EvictionImpact::FullyEvicted),
                (2, EvictionImpact::Unchanged),
                (3, EvictionImpact::FullyEvicted),
            ],
            positions_evicted: vec![(0, 0..10)],
        };

        assert!(result.has_fully_evicted());
        let evicted_ids = result.fully_evicted_span_ids();
        assert_eq!(evicted_ids.len(), 2);
        assert!(evicted_ids.contains(&1));
        assert!(evicted_ids.contains(&3));
    }
}
